name: modemart
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Application version number (X.Y.Z) and build number (+N).
version: 1.0.0+1

# Dart SDK version constraint.
environment:
  sdk: ^3.10.0

# Packages required for the application to run.
dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8

  # State Mangement
  get: ^4.7.2
  get_storage: ^2.1.1
  

  # Product Spcific
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  any_image_view: ^1.9.0

# Packages used only during development/testing.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter specific configuration section.
flutter:
  # Enables Material Icons font.
  uses-material-design: true

  # ---------------------- Local Assets ----------------------
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/profile/
    - assets/icons/payment_methods/

  # --------------------- Local fonts -----------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800